### ISSUE TITLE
Invalid function call in typography.scss

### ISSUE THREAD

**Issue by AshD93** [roikles/Flexbones#31]
Line 22 + 28 need "color" renaming to "clr" in order to make use of the function correctly.

Change to:
```scss
// Links
a {
    color: clr(link,default);
    ...
}
    // Link hover state
    a:hover{
        color: clr(link,hover);
    }
```
